
data_conf:
  train_conf:
    proxy_conf:
      data_path: "/media/dell/workspace/workspace_lzy/lzy/proxyremotefinterprinting/code/interval_defined_burst_reshaping/dataset/json/hsproxy_data_tcpinfo.json"
      inthr: 0.1
      ncpp: 0.0
      train_rate: 1
      type_list:
        - "raw_seqs"
        
    hs_conf:
      data_path: "/media/dell/workspace/workspace_lzy/lzy/proxyremotefinterprinting/code/interval_defined_burst_reshaping/dataset/json/hs_data_train_tcpinfo.json"
      inthr: 0.05
      ncpp: 0.0
      train_rate: 1
      type_list:
        - "raw_seqs"


  test_conf:
    data_path: "/media/dell/workspace/workspace_lzy/lzy/proxyremotefinterprinting/code/interval_defined_burst_reshaping/dataset/json/hs_data_test_tcpinfo.json"
    inthr: 0.05
    ncpp: 0.0
    train_rate: 0
    type_list:
      - "raw_seqs"

model_conf:
  length: 5000
  nb_class: 103
  batch_size: 128
  nb_epoch: 50
  save_path: "./saved_model"
  save_name_head: "idea_DF"
  pseudo_steps: 6

