
data_conf:
  train_conf:
    proxy_conf:
      data_path: "/media/dell/workspace/workspace_lzy/lzy/proxyremotefinterprinting/code/interval_defined_burst_reshaping/dataset/json/hsproxy_data_tcpinfo.json"
      inthr: 0.1
      ncpp: 0.0
      train_rate: 1
      type_list:
        - "raw_seqs"
        - "burst_reshaping"

    hs_conf:
      data_path: "/media/dell/workspace/workspace_lzy/lzy/proxyremotefinterprinting/code/interval_defined_burst_reshaping/dataset/json/hs_data_train_tcpinfo.json"
      inthr: 0.05
      ncpp: 0.0
      train_rate: 0.2
      type_list:
        - "raw_seqs"
        - "burst_reshaping"

  test_conf:
    data_path: "/media/dell/workspace/workspace_lzy/lzy/proxyremotefinterprinting/code/interval_defined_burst_reshaping/dataset/json/hs_data_test_tcpinfo.json"
    inthr: 0.05
    ncpp: 0.0
    train_rate: 0
    type_list:
      - "burst_reshaping"

model_conf:
  init_epoch: 15
  length: 5000
  nb_class: 103
  batch_size: 128
  nb_epoch: 40
  save_path: "./params_model/"
  save_name_head: "Pseudolabel_DF"
  pseudo_per_epoch: 5
  confidence_threshold: 0.95
  save_model: true